# Generated by Django 5.2.8 on 2025-11-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
    ]
